project:
  type: website

website:
  title: "Group 10 Cost of Coast?"
  navbar:
    left:
      - href: overview.html
        text: Overview
      - href: Poster.html
        text: Poster
      - href: methodology.html
        text: Methodology
      - href: analysis.html
        text: Analysis
      - href: results_discussion.html
        text: Results & Discussion
    right:
      - href: index.html
        text: Home
      - href: about.html
        text: About
        
format:
  html:
    theme: Lumen
    css: styles.css
    toc: true

editor: visual

