---
title: "Overview"
editor: visual
---

## Overview

Our project aims to find out who the main target audience is for the upcoming stage 4 of Thomson-East Coast Line and whether it is worth the continuous large investments. The main tool we used on QGIS was Iso-Area as Polygons, to delineate the Catchment Area of each MRT station.

The main tool used to generate these iso-areas were the pathways that people can walk on, which included every single road in Singapore except for expressways. Further analyses was done to extract the places of interest that are available within each catchment area. These are possible with the help of open source data from data.gov.sg and OpenStreetMap. With these data, we were able to find the immediate catchment area of the stations and learn what facilities and services are provided. From this, we were able to draw inferences as to who is the main demographic that would be using the new stations and a bit on their socio-economic status.

Our key findings included analyzing which MRT stations are redundant or important to improving transportational links, finding out the minutes saved when one chooses to cycle instead of walking, and analyzing the services that are provided within each well-defined catchment area. We then proceeded to offer our recommendations to further enhance the connectivity between residences and educational institutions and drew conclusions to sum up our objectives.

We did find out that there were some MRT stations that served a greater purpose than others just as we expected. Being in close proximity with the East-West line and Circle Line, we found that there are multiple stations whose Iso-Areas would overlap with the existing ones. Furthermore, some stations served largely people that stayed in landed property who may highly likely already own private vehicles. Hence, some recommendations we proposed include improving the current bus services to increase connectivity and use resources efficiently.
