---
title: "Results & Discussion"
editor: visual
---

# Results & Discussion

To answer our problem statement, \'Do some MRTs serve a greater purpose than others?\', from our analysis, we can conclude that this statement is true to a great extent. 

Through the studying of the catchment areas of the upcoming TEL MRT stations, comparing it with the existing MRT lines, it is clear that the construction of some TEL MRT stations may not be wholly necessary, even though it increases the convenience of a certain population. For example, by analysing Siglap MRT station, the immediate catchment area (less than 10-minute walk away) are many low-rise residential buildings. As we learn more through Google Street View, we found that the majority of these buildings are landed properties. This gives us an idea that hints the people this MRT is serving might be the wealthier demographic, which may not even have much need for the MRT stations in the first place due to the presence of private vehicles. However, such an assumption may be far-reaching as children or students may still need public transport. Even so, this might still not justify the high costs of building this MRT station as the number of population in that area is much less than catchment areas that are predominantly HDBs. HDB can house significantly more people than landed properties. One HDB block can house around 440 people (based on our assumption below) while landed property can house around 10 for the same land area. 

We recommend that the government can look more into improving the bus services in areas that are not as densely populated. Bus services are much cheaper to implement compared to building a whole MRT station, which amounts to [great construction costs](https://www.lta.gov.sg/content/ltagov/en/newsroom/2016/3/2/lta-awards-contract-to-build-worlds-first-four-in-one-depot.html). We looked up the available bus services in Siglap, and realised that there are only two bus services 40 and 401 respectively, which connect routes within the [Bedok Planning Area](https://www.transitlink.com.sg/eservice/eguide/road_info.php?road_name=Siglap+Rd). We feel that more resources could be diverted to the implementation of bus services instead, so that the residents in the area could better access other parts of Singapore, without the presence of an MRT station. 

According to Mr Ang Wei Neng from LTA, he says that the new MRT stations would cause a fall in the ridership in parallel bus services and would in turn require more public funds and subsidies to keep the bus services going. However, they also mentioned that there is still a need for bus services with low ridership as they serve areas that [need connectivity](https://www.straitstimes.com/singapore/parliament-only-two-feeder-bus-services-generated-enough-revenue-to-cover-operating-costs). Therefore, our group proposes that more emphasis should be placed in improving the bus routes to encourage greater use of buses instead of investing a large sum into building MRT stations. Rather than pooling resources to run both the bus service and MRT, more resources should be invested to perfect the existing bus service to provide connectivity everywhere.

By diving deeper into the placements of these MRT stations, we can see that some of these MRT stations reap a marginal increase in convenience as compared to the others. For example, we found that TE23 (Tanjong Rhu) is in close proximity to CC6 (Stadium) Although there are plans to build more residential buildings around Tanjong Rhu, these can still easily be served by the addition of additional bus routes, which costs significantly less as mentioned above. The same story can be said about TE26 (Marine Parade) & TE27 (Marine Terrace) which are, in terms of walking time, approximately 5-10 minutes apart from each other. Taking the example of DT4 (Hume), SMRT & LTA can consider making any of the aforementioned stations a shell station (an inactive station) until they can justify that there is a significant need to balance out the growth of ridership.

The overall benefit that the new MRT stations can bring should not be overlooked, however. Given the roads around the upcoming MRT stations can be very congested during the rush hour periods, the new stations could alleviate the congestion around the area, as well as reducing travelling times for people rushing home from work. Considering our targeted study areas contain a fair number of educational institutions. For example, students could choose to take the MRT rather than taking buses or having their parents drive their private vehicle, providing students with alternative & potentially faster routes back home, especially if their place of residence is in the north.

Assumption: 

Number of people living in one HDB building = [4.3](https://www.teoalida.com/singapore/hdbstatistics/) x 6 x 17 = 438.6 (round up to 440)

\

